apiVersion: v1
kind: Service
metadata:
    name: "mopictestclusterdy-e4f1"
    labels:
        app: "mopictestclusterdy-e4f1"
spec:
    type: LoadBalancer
    ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
    selector:
        app: "mopictestclusterdy-e4f1"